# Generated by Django 4.1.3 on 2022-11-30 01:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=30)),
                ('exterior_number', models.CharField(max_length=8)),
                ('interior_number', models.CharField(blank=True, max_length=5)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('municipality', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.address')),
            ],
        ),
    ]
