# Generated by Django 4.1.3 on 2022-11-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
