# Generated by Django 4.1.2 on 2022-11-07 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('basic_basket_supply', models.FloatField(default=0.0)),
                ('basic_basket_demand', models.FloatField(default=0.0)),
                ('fruits_and_vegetables_supply', models.FloatField(default=0.0)),
                ('fruits_and_vegetables_demand', models.FloatField(default=0.0)),
                ('dairy_supply', models.FloatField(default=0.0)),
                ('dairy_demand', models.FloatField(default=0.0)),
                ('inedibles_supply', models.FloatField(default=0.0)),
                ('inedibles_demand', models.FloatField(default=0.0)),
            ],
        ),
    ]
