# Generated by Django 4.1.3 on 2022-11-21 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='basic_basket_demand',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='basic_basket_supply',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='dairy_demand',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='dairy_supply',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='fruits_and_vegetables_demand',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='fruits_and_vegetables_supply',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inedibles_demand',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inedibles_supply',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('BB', 'Basic Basket'), ('FV', 'Fruits and Vegetables'), ('DA', 'Dairy'), ('IE', 'Inedibles'), ('GR', 'Groceries')], default='BB', max_length=2),
        ),
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventory',
            name='demand',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supply',
            field=models.FloatField(default=0.0),
        ),
    ]
