# Generated by Django 4.1.3 on 2022-11-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_basic_basket_demand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
