# Generated by Django 4.1.3 on 2022-11-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_date_inventory_month_inventory_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('BB', 'Basic Basket'), ('FV', 'Fruits and Vegetables'), ('DA', 'Dairy'), ('IE', 'Inedibles'), ('GR', 'Groceries')], max_length=2),
        ),
    ]
