# Generated by Django 4.1.3 on 2022-11-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('BB', 'Basic Basket'), ('FV', 'Fruits and Vegetables'), ('DA', 'Dairy'), ('IE', 'Inedibles'), ('GR', 'Groceries')], default='BB', max_length=2),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=11),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
