# Generated by Django 4.1.3 on 2022-11-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_category_alter_inventory_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='examples',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
