# Generated by Django 4.1.3 on 2022-11-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_examples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='examples',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
