# Generated by Django 4.1.3 on 2022-11-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_alter_contributor_second_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='interior_number',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
