# Generated by Django 4.1.3 on 2022-11-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
