name: Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run backend unit tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup python 3.10.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8

      - name: Install pipenv
        run: pip install pipenv

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs/
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          cd server
          pipenv install --dev

      - name: Run tests
        run: |
          cd server/food_bank_app
          pipenv run python manage.py test
