name: Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run frontend unit tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup node TS enviornment
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0
      - name: Install Dependencies
        run: |
          cd food-bank-app
          npm ci
      - name: Run tests
        run: |
          cd food-bank-app
          npm run test